// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(FormulaRaceContext))]
    partial class FormulaRaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Core.Entities.team_drivers", b =>
                {
                    b.Property<int>("Team_Id")
                        .HasColumnType("int");

                    b.Property<int>("Driver_Id")
                        .HasColumnType("int");

                    b.HasKey("Team_Id", "Driver_Id");

                    b.HasIndex("Driver_Id");

                    b.ToTable("team_drivers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.team_drivers", b =>
                {
                    b.HasOne("Core.Entities.Team", "Team")
                        .WithMany("Team_Drivers")
                        .HasForeignKey("Driver_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Driver", "Driver")
                        .WithMany("Team_Drivers")
                        .HasForeignKey("Team_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Core.Entities.Driver", b =>
                {
                    b.Navigation("Team_Drivers");
                });

            modelBuilder.Entity("Core.Entities.Team", b =>
                {
                    b.Navigation("Team_Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
